----------------------------------
--<!>-- BOII | DEVELOPMENT --<!>--
----------------------------------

--<!>-- LANGUAGE SETTINGS --<!>--
Language = {
    Targeting = {
        ['dutyicon'] = 'fas fa-clipboard', -- Icon used by qb-target for on duty location visit; https://fontawesome.com to change
        ['dutylabel'] = 'Clock In/Out', -- Label used by qb-target for on duty location
        ['bossicon'] = 'fas fa-clipboard-list', -- Icon used by qb-target for boss menu location visit; https://fontawesome.com to change
        ['bosslabel'] = 'Open Job Management', -- Label used by qb-target for boss menu location
        ['bossstorageicon'] = 'fas fa-box', -- Icon used by qb-target for boss storage locations visit; https://fontawesome.com to change
        ['bossstoragelabel'] = 'Open Management Storage', -- Label used by qb-target for boss storage locations
        ['jobstorageicon'] = 'fas fa-box', -- Icon used by qb-target for job storage locations visit; https://fontawesome.com to change
        ['jobstoragelabel'] = 'Open Storage', -- Label used by qb-target for job storage locations
        ['traystorageicon'] = 'fas fa-shopping-cart', -- Icon used by qb-target for tray storage locations visit; https://fontawesome.com to change
        ['traystoragelabel'] = 'Collect Order', -- Label used by qb-target for tray storage locations
        ['eposicon'] = 'fas fa-cash-register', -- Icon used by qb-target for payment locations visit; https://fontawesome.com to change
        ['eposlabel'] = 'Charge Customer', -- Label used by qb-target for payment locations
        ['storeicon'] = 'fas fa-shopping-basket', -- Icon used by qb-target for job location visit; https://fontawesome.com to change
        ['storelabel'] = 'Purchase Stock', -- Label used by qb-target for store location
        ['outfiticon'] = 'fas fa-shirt', -- Icon used by qb-target for wardrobe locations visit; https://fontawesome.com to change
        ['outfitlabel'] = 'Change Outfit', -- Label used by qb-target for wardrobe locations
        ['washicon'] = 'fas fa-hands-wash', -- Icon used by qb-target for washing locations visit; https://fontawesome.com to change
        ['washfacelabel'] = 'Wash Face', -- Label used by qb-target for washing locations  
        ['washhandslabel'] = 'Wash Hands', -- Label used by qb-target for washing locations
        ['washdishesicon'] = 'fas fa-sink', -- Icon used by qb-target for dishwash location visit; https://fontawesome.com to change
        ['platelabel'] = 'Wash Plate', -- Label used by qb-target for washing plates at dishwash location
        ['bowllabel'] = 'Wash Bowl', -- Label used by qb-target for washing bowls at dishwash location
        ['cuplabel'] = 'Wash Cup', -- Label used by qb-target for washing cups at dishwash location
        ['glasslabel'] = 'Wash Glass', -- Label used by qb-target for washing glasses at dishwash location
        ['bentolabel'] = 'Wash Bento', -- Label used by qb-target for washing bento box at dishwash location
        ['garageicon'] = 'fas fa-car', -- Icon used by qb-target for garage location visit; https://fontawesome.com to change
        ['garagelabel'] = 'Company Vehicle', -- Label used by qb-target for garage location
        ['hotdrinksicon'] = 'fas fa-coffee', -- Icon used by qb-target for hot drinks location visit; https://fontawesome.com to change
        ['hotdrinkslabel'] = 'Make A Hot Drink', -- Label used by qb-target hot drinks location
        ['hobicon'] = 'fa-solid fa-fire', -- Icon used by qb-target for hob location visit; https://fontawesome.com to change
        ['hoblabel'] = 'Use Hob', -- Label used by qb-target for hob location
        ['ovenicon'] = 'fas fa-fire-alt', -- Icon used by qb-target for oven location visit; https://fontawesome.com to change
        ['ovenlabel'] = 'Use Oven', -- Label used by qb-target for oven location
        ['cuttingboardicon'] = 'fa-solid fa-utensils', -- Icon used by qb-target for cutting board location visit; https://fontawesome.com to change
        ['cuttingboardlabel'] = 'Use Cutting Board', -- Label used by qb-target for cutting board location
        ['mixericon'] = 'fa-solid fa-stroopwafel', -- Icon used by qb-target for mixer location visit; https://fontawesome.com to change
        ['mixerlabel'] = 'Use Mixer', -- Label used by qb-target for mixer location
        ['glassesicon'] = 'fa-solid fa-glass-water', -- Icon used by qb-target for glasses locations visit; https://fontawesome.com to change
        ['takeglasslabel'] = 'Take A Glass', -- Label used by qb-target for taking a glass from glasses locations
        ['storeglasslabel'] = 'Put Away Glass', -- Label used by qb-target for storing a glass in glasses locations
        ['bowlsicon'] = 'fa-solid fa-glass-water', -- Icon used by qb-target for bowls locations visit; https://fontawesome.com to change
        ['takebowllabel'] = 'Take A Bowl', -- Label used by qb-target for taking a bowl from bowls locations
        ['storebowllabel'] = 'Put Away Bowl', -- Label used by qb-target for storing a bowl in bowls locations
        ['platesicon'] = 'fa-solid fa-earth-oceania', -- Icon used by qb-target for plates location visit; https://fontawesome.com to change
        ['takeplatelabel'] = 'Take A Plate', -- Label used by qb-target for taking a plate from plates location
        ['storeplatelabel'] = 'Put Away Plate', -- Label used by qb-target for storing a plate in plates location
        ['bentoicon'] = 'fa-solid fa-earth-oceania', -- Icon used by qb-target for plates location visit; https://fontawesome.com to change
        ['takebentolabel'] = 'Take A Bento Box', -- Label used by qb-target for taking a bento box from bento location
        ['storebentolabel'] = 'Put Away Bento Box', -- Label used by qb-target for storing a bento box from bento location
        ['cupsicon'] = 'fa-solid fa-mug-hot', -- Icon used by qb-target for cups location visit; https://fontawesome.com to change
        ['takecuplabel'] = 'Take A Cup', -- Label used by qb-target for taking cup from cups location
        ['storecuplabel'] = 'Put Away Cup', -- Label used by qb-target for storing cup in cups location
        ['caticon'] = 'fas fa-cat', -- Icon used by qb-target for cats visit; https://fontawesome.com to change
        ['catlabel'] = 'Pet The Cat', -- Label used by qb-target for cats 
    },
    Duty = {
        ['dutymenuheader'] = 'Staff Duty', -- Menu header
        ['dutymenuheadertext'] = 'Clock in and out of duty here!', -- Menu header text
        ['dutymenuheadericon'] = 'fa-solid fa-briefcase', -- Menu header icon
        ['dutytoggle'] = '• Clock In/Out', -- Menu header
        ['dutytoggleicon'] = 'fa-solid fa-clock' -- Menu header icon
    },
    Hob = {
        ['hotfoodheader'] = 'Hot Food Station', -- Menu header
        ['hotfoodheadertext'] = 'Prepare hot food!', -- Menu header text
        ['hotfoodheadericon'] = 'fa-solid fa-briefcase', -- Menu header icon
        ['hotfoodicon'] = 'fa-solid fa-bowl-food', -- Menu header icon
        ['bentoheader'] = 'Bento Boxes', -- Menu header
        ['bentoheadertext'] = 'Prepare bento boxes for your customers!', -- Menu header text
        ['bentoheadericon'] = 'fa-solid fa-fire-burner',
        ['bentoheader1'] = 'Aji Bento', -- Menu header
        ['bentoheadertext1'] = 'Ingredients:</p>'..Config.Food.Hob.Bento.Aji.Required['1'].amount..'x '..Config.Food.Hob.Bento.Aji.Required['1'].label..'</p>'..Config.Food.Hob.Bento.Aji.Required['2'].amount..'x '..Config.Food.Hob.Bento.Aji.Required['2'].label..'</p>'..Config.Food.Hob.Bento.Aji.Required['3'].amount..'x '..Config.Food.Hob.Bento.Aji.Required['3'].label, -- Menu header text
        ['bentoheader2'] = 'Inada Bento', -- Menu header
        ['bentoheadertext2'] = 'Ingredients:</p>'..Config.Food.Hob.Bento.Inada.Required['1'].amount..'x '..Config.Food.Hob.Bento.Inada.Required['1'].label..'</p>'..Config.Food.Hob.Bento.Inada.Required['2'].amount..'x '..Config.Food.Hob.Bento.Inada.Required['2'].label..'</p>'..Config.Food.Hob.Bento.Inada.Required['3'].amount..'x '..Config.Food.Hob.Bento.Inada.Required['3'].label, -- Menu header text
        ['bentoheader3'] = 'Akou-Dai Bento', -- Menu header
        ['bentoheadertext3'] = 'Ingredients:</p>'..Config.Food.Hob.Bento.Akoudai.Required['1'].amount..'x '..Config.Food.Hob.Bento.Akoudai.Required['1'].label..'</p>'..Config.Food.Hob.Bento.Akoudai.Required['2'].amount..'x '..Config.Food.Hob.Bento.Akoudai.Required['2'].label..'</p>'..Config.Food.Hob.Bento.Akoudai.Required['3'].amount..'x '..Config.Food.Hob.Bento.Akoudai.Required['3'].label, -- Menu header text
        ['bentoheader4'] = 'Katsu Chicken Bento', -- Menu header
        ['bentoheadertext4'] = 'Ingredients:</p>'..Config.Food.Hob.Bento.Katsu.Required['1'].amount..'x '..Config.Food.Hob.Bento.Katsu.Required['1'].label..'</p>'..Config.Food.Hob.Bento.Katsu.Required['2'].amount..'x '..Config.Food.Hob.Bento.Katsu.Required['2'].label..'</p>'..Config.Food.Hob.Bento.Katsu.Required['3'].amount..'x '..Config.Food.Hob.Bento.Katsu.Required['3'].label, -- Menu header text
        ['bentoheader5'] = 'Chashu Bento', -- Menu header
        ['bentoheadertext5'] = 'Ingredients:</p>'..Config.Food.Hob.Bento.Chashu.Required['1'].amount..'x '..Config.Food.Hob.Bento.Chashu.Required['1'].label..'</p>'..Config.Food.Hob.Bento.Chashu.Required['2'].amount..'x '..Config.Food.Hob.Bento.Chashu.Required['2'].label..'</p>'..Config.Food.Hob.Bento.Chashu.Required['3'].amount..'x '..Config.Food.Hob.Bento.Chashu.Required['3'].label, -- Menu header text
        ['ramenheader'] = 'Ramen Bowls', -- Menu header
        ['ramenheadertext'] = 'Prepare ramen bowls for your customers!', -- Menu header text
        ['ramenheadericon'] = 'fa-solid fa-fire-burner',
        ['ramenheader1'] = 'Iwashi Ramen', -- Menu header
        ['ramenheadertext1'] = 'Required:</p>1x Ramen Bowl</p>2x Sardine</p>1x Ramen Noodles', -- Menu header text
        ['ramenheader2'] = 'Aji Ramen', -- Menu header
        ['ramenheadertext2'] = 'Required:</p>1x Ramen Bowl</p>2x Mackerel</p>1x Ramen Noodles', -- Menu header text
        ['ramenheader3'] = 'O-hyou Ramen', -- Menu header
        ['ramenheadertext3'] = 'Required:</p>1x Ramen Bowl</p>1x Halibut</p>1x Ramen Noodles', -- Menu header text
        ['ramenheader4'] = 'Chicken Ramen', -- Menu header
        ['ramenheadertext4'] = 'Required:</p>1x Ramen Bowl</p>2x Chicken Meat</p>1x Ramen Noodles', -- Menu header text
        ['ramenheader5'] = 'Beef Ramen', -- Menu header
        ['ramenheadertext5'] = 'Required:</p>1x Ramen Bowl</p>1x Beef</p>1x Ramen Noodles', -- Menu header text
        Bento = {
            ['nobento'] = 'You need a '..Config.Food.Hob.Bento.Required.label, -- Notification
            ['noaji1'] = 'You dont have any '..Config.Food.Hob.Bento.Aji.Required['1'].label, -- Notification
            ['noaji2'] = 'You dont have any '..Config.Food.Hob.Bento.Aji.Required['2'].label, -- Notification
            ['noaji3'] = 'You dont have any '..Config.Food.Hob.Bento.Aji.Required['3'].label, -- Notification
            ['enoughaji1'] = 'You dont have enough '..Config.Food.Hob.Bento.Aji.Required['1'].label, -- Notification
            ['enoughaji2'] = 'You dont have enough '..Config.Food.Hob.Bento.Aji.Required['2'].label, -- Notification
            ['enoughaji3'] = 'You dont have enough '..Config.Food.Hob.Bento.Aji.Required['3'].label, -- Notification
            ['noinada1'] = 'You dont have any '..Config.Food.Hob.Bento.Inada.Required['1'].label, -- Notification
            ['noinada2'] = 'You dont have any '..Config.Food.Hob.Bento.Inada.Required['2'].label, -- Notification
            ['noinada3'] = 'You dont have any '..Config.Food.Hob.Bento.Inada.Required['3'].label, -- Notification
            ['enoughinada1'] = 'You dont have enough '..Config.Food.Hob.Bento.Inada.Required['1'].label, -- Notification
            ['enoughinada2'] = 'You dont have enough '..Config.Food.Hob.Bento.Inada.Required['2'].label, -- Notification
            ['enoughinada3'] = 'You dont have enough '..Config.Food.Hob.Bento.Inada.Required['3'].label, -- Notification
            ['noakoudai1'] = 'You dont have any '..Config.Food.Hob.Bento.Akoudai.Required['1'].label, -- Notification
            ['noakoudai2'] = 'You dont have any '..Config.Food.Hob.Bento.Akoudai.Required['2'].label, -- Notification
            ['noakoudai3'] = 'You dont have any '..Config.Food.Hob.Bento.Akoudai.Required['3'].label, -- Notification
            ['enoughakoudai1'] = 'You dont have enough '..Config.Food.Hob.Bento.Akoudai.Required['1'].label, -- Notification
            ['enoughakoudai2'] = 'You dont have enough '..Config.Food.Hob.Bento.Akoudai.Required['2'].label, -- Notification
            ['enoughakoudai3'] = 'You dont have enough '..Config.Food.Hob.Bento.Akoudai.Required['3'].label, -- Notification
            ['nokatsu1'] = 'You dont have any '..Config.Food.Hob.Bento.Katsu.Required['1'].label, -- Notification
            ['nokatsu2'] = 'You dont have any '..Config.Food.Hob.Bento.Katsu.Required['2'].label, -- Notification
            ['nokatsu3'] = 'You dont have any '..Config.Food.Hob.Bento.Katsu.Required['3'].label, -- Notification
            ['enoughkatsu1'] = 'You dont have enough '..Config.Food.Hob.Bento.Katsu.Required['1'].label, -- Notification
            ['enoughkatsu2'] = 'You dont have enough '..Config.Food.Hob.Bento.Katsu.Required['2'].label, -- Notification
            ['enoughkatsu3'] = 'You dont have enough '..Config.Food.Hob.Bento.Katsu.Required['3'].label, -- Notification
            ['nochasu1'] = 'You dont have any '..Config.Food.Hob.Bento.Chashu.Required['1'].label, -- Notification
            ['nochasu2'] = 'You dont have any '..Config.Food.Hob.Bento.Chashu.Required['2'].label, -- Notification
            ['nochasu3'] = 'You dont have any '..Config.Food.Hob.Bento.Chashu.Required['3'].label, -- Notification
            ['enoughchasu1'] = 'You dont have enough '..Config.Food.Hob.Bento.Chashu.Required['1'].label, -- Notification
            ['enoughchasu2'] = 'You dont have enough '..Config.Food.Hob.Bento.Chashu.Required['2'].label, -- Notification
            ['enoughchasu3'] = 'You dont have enough '..Config.Food.Hob.Bento.Chashu.Required['3'].label, -- Notification
            ['madebento'] = 'You successfully prepared a Bento Box!', -- Notification
            ['makebento'] = 'Preparing Bento Box..', -- Progressbar
        },
        Ramen = {
            ['nobowl'] = 'You need a '..Config.Food.Hob.Ramen.Required.label, -- Notification
            ['noiwashi1'] = 'You dont have any '..Config.Food.Hob.Ramen.Iwashi.Required['1'].label, -- Notification
            ['noiwashi2'] = 'You dont have any '..Config.Food.Hob.Ramen.Iwashi.Required['2'].label, -- Notification
            ['enoughiwashi1'] = 'You dont have enough '..Config.Food.Hob.Ramen.Iwashi.Required['1'].label, -- Notification
            ['enoughiwashi2'] = 'You dont have enough '..Config.Food.Hob.Ramen.Iwashi.Required['2'].label, -- Notification
            ['noaji1'] = 'You dont have any '..Config.Food.Hob.Ramen.Aji.Required['1'].label, -- Notification
            ['noaji2'] = 'You dont have any '..Config.Food.Hob.Ramen.Aji.Required['2'].label, -- Notification
            ['enoughaji1'] = 'You dont have enough '..Config.Food.Hob.Ramen.Aji.Required['1'].label, -- Notification
            ['enoughaji2'] = 'You dont have enough '..Config.Food.Hob.Ramen.Aji.Required['2'].label, -- Notification
            ['noohyou1'] = 'You dont have any '..Config.Food.Hob.Ramen.Ohyou.Required['1'].label, -- Notification
            ['noohyou2'] = 'You dont have any '..Config.Food.Hob.Ramen.Ohyou.Required['2'].label, -- Notification
            ['enoughohyou1'] = 'You dont have enough '..Config.Food.Hob.Ramen.Ohyou.Required['1'].label, -- Notification
            ['enoughohyou2'] = 'You dont have enough '..Config.Food.Hob.Ramen.Ohyou.Required['2'].label, -- Notification
            ['nochicken1'] = 'You dont have any '..Config.Food.Hob.Ramen.Chicken.Required['1'].label, -- Notification
            ['nochicken2'] = 'You dont have any '..Config.Food.Hob.Ramen.Chicken.Required['2'].label, -- Notification
            ['enoughchicken1'] = 'You dont have enough '..Config.Food.Hob.Ramen.Chicken.Required['1'].label, -- Notification
            ['enoughchicken2'] = 'You dont have enough '..Config.Food.Hob.Ramen.Chicken.Required['2'].label, -- Notification
            ['nobeef1'] = 'You dont have any '..Config.Food.Hob.Ramen.Beef.Required['1'].label, -- Notification
            ['nobeef2'] = 'You dont have any '..Config.Food.Hob.Ramen.Beef.Required['2'].label, -- Notification
            ['enoughbeef1'] = 'You dont have enough '..Config.Food.Hob.Ramen.Beef.Required['1'].label, -- Notification
            ['enoughbeef2'] = 'You dont have enough '..Config.Food.Hob.Ramen.Beef.Required['2'].label, -- Notification
            ['maderamen'] = 'You successfully prepared a Ramen Bowl!', -- Notification
            ['makeramen'] = 'Preparing Ramen..', -- Progressbar
        }
    },
    Cuttingboard = {
        ['coldfoodheader'] = 'Cutting Board', -- Menu header
        ['coldfoodheadertext'] = 'Prepare cold food!', -- Menu header text
        ['coldfoodheadericon'] = 'fa-solid fa-briefcase', -- Menu header icon
        ['noknife'] = 'You dont have a '..Config.Food.Cuttingboard.Required['1'].label, -- Notification
        ['noplate'] = 'You dont have a '..Config.Food.Cuttingboard.Required['2'].label, -- Notification
        Sushi = {
            ['sushiheader'] = 'Sushi Recipes', -- Menu header
            ['sushiheadertext'] = 'View sushi recipes!', -- Menu header text
            ['sushiheadericon'] = 'fa-solid fa-fish-fins', -- Menu header icon
            ['sushiicon'] = 'fa-solid fa-fish-fins', -- Menu header icon
            ['sushiheader1'] = 'Iwashi Sushi', -- Menu header
            ['sushiheadertext1'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sushi.Iwashi.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Iwashi.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['2'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Iwashi.Required['3'].amount..'x '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['3'].label, -- Menu header text
            ['sushiheader2'] = 'Inada Sushi', -- Menu header
            ['sushiheadertext2'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sushi.Inada.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sushi.Inada.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Inada.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sushi.Inada.Required['2'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Inada.Required['3'].amount..'x '..Config.Food.Cuttingboard.Sushi.Inada.Required['3'].label, -- Menu header text
            ['sushiheader3'] = 'Ishimochi Guchi Sushi', -- Menu header
            ['sushiheadertext3'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sushi.Guchi.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sushi.Guchi.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Guchi.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sushi.Guchi.Required['2'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Guchi.Required['3'].amount..'x '..Config.Food.Cuttingboard.Sushi.Guchi.Required['3'].label, -- Menu header text
            ['sushiheader4'] = 'Akou-Dai Sushi', -- Menu header
            ['sushiheadertext4'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sushi.Akoudai.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Akoudai.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['2'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Akoudai.Required['3'].amount..'x '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['3'].label, -- Menu header text
            ['sushiheader5'] = 'O-hyou Sushi', -- Menu header
            ['sushiheadertext5'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sushi.Ohyou.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Ohyou.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['2'].label..'</p>'..Config.Food.Cuttingboard.Sushi.Ohyou.Required['3'].amount..'x '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['3'].label, -- Menu header text
            ['noiwashi1'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['1'].label, -- Notification
            ['noiwashi2'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['2'].label, -- Notification
            ['noiwashi3'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['3'].label, -- Notification
            ['enoughiwashi1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['1'].label, -- Notification
            ['enoughiwashi2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['2'].label, -- Notification
            ['enoughiwashi3'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Iwashi.Required['3'].label, -- Notification
            ['noinada1'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Inada.Required['1'].label, -- Notification
            ['noinada2'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Inada.Required['2'].label, -- Notification
            ['noinada3'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Inada.Required['3'].label, -- Notification
            ['enoughinada1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Inada.Required['1'].label, -- Notification
            ['enoughinada2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Inada.Required['2'].label, -- Notification
            ['enoughinada3'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Inada.Required['3'].label, -- Notification
            ['noguchi1'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Guchi.Required['1'].label, -- Notification
            ['noguchi2'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Guchi.Required['2'].label, -- Notification
            ['noguchi3'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Guchi.Required['3'].label, -- Notification
            ['enoughguchi1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Guchi.Required['1'].label, -- Notification
            ['enoughguchi2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Guchi.Required['2'].label, -- Notification
            ['enoughguchi3'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Guchi.Required['3'].label, -- Notification
            ['noakoudai1'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['1'].label, -- Notification
            ['noakoudai2'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['2'].label, -- Notification
            ['noakoudai3'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['3'].label, -- Notification
            ['enoughakoudai1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['1'].label, -- Notification
            ['enoughakoudai2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['2'].label, -- Notification
            ['enoughakoudai3'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Akoudai.Required['3'].label, -- Notification
            ['noohyou1'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['1'].label, -- Notification
            ['noohyou2'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['2'].label, -- Notification
            ['noohyou3'] = 'You dont have any '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['3'].label, -- Notification
            ['enoughohyou1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['1'].label, -- Notification
            ['enoughohyou2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['2'].label, -- Notification
            ['enoughohyou3'] = 'You dont have enough '..Config.Food.Cuttingboard.Sushi.Ohyou.Required['3'].label, -- Notification
            ['madesushi'] = 'You successfully prepared some sushi!', -- Notification
            ['makesushi'] = 'Preparing Sushi..', -- Progressbar
        },
        Sashimi = {
            ['sashimiheader'] = 'Sashimi Recipes', -- Menu header
            ['sashimiheadertext'] = 'View sashimi recipes!', -- Menu header text
            ['sashimiheadericon'] = 'fa-solid fa-fish-fins', -- Menu header icon
            ['sashimiicon'] = 'fa-solid fa-shrimp', -- Menu header icon
            ['sashimiheader1'] = 'Aji Sashimi', -- Menu header
            ['sashimiheadertext1'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sashimi.Aji.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Aji.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sashimi.Aji.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Aji.Required['2'].label, -- Menu header text
            ['sashimiheader2'] = 'Akou-Dai Sashimi', -- Menu header
            ['sashimiheadertext2'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sashimi.Akoudai.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Akoudai.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sashimi.Akoudai.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Akoudai.Required['2'].label, -- Menu header text
            ['sashimiheader3'] = 'O-hyou Sashimi', -- Menu header
            ['sashimiheadertext3'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sashimi.Ohyou.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Ohyou.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sashimi.Ohyou.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Ohyou.Required['2'].label, -- Menu header text
            ['sashimiheader4'] = 'Beef Sashimi', -- Menu header
            ['sashimiheadertext4'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sashimi.Beef.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Beef.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sashimi.Beef.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Beef.Required['2'].label, -- Menu header text
            ['sashimiheader5'] = 'Venison Sashimi', -- Menu header
            ['sashimiheadertext5'] = 'Ingredients:</p>'..Config.Food.Cuttingboard.Sashimi.Venison.Required['1'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Venison.Required['1'].label..'</p>'..Config.Food.Cuttingboard.Sashimi.Venison.Required['2'].amount..'x '..Config.Food.Cuttingboard.Sashimi.Venison.Required['2'].label, -- Menu header text
            ['noaji1'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Aji.Required['1'].label, -- Notification
            ['noaji2'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Aji.Required['2'].label, -- Notification
            ['enoughaji1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Aji.Required['1'].label, -- Notification
            ['enoughaji2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Aji.Required['2'].label, -- Notification
            ['noakoudai1'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Akoudai.Required['1'].label, -- Notification
            ['noakoudai2'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Akoudai.Required['2'].label, -- Notification
            ['enoughakoudai1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Akoudai.Required['1'].label, -- Notification
            ['enoughakoudai2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Akoudai.Required['2'].label, -- Notification
            ['noohyou1'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Ohyou.Required['1'].label, -- Notification
            ['noohyou2'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Ohyou.Required['2'].label, -- Notification
            ['enoughohyou1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Ohyou.Required['1'].label, -- Notification
            ['enoughohyou2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Ohyou.Required['2'].label, -- Notification
            ['nobeef1'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Beef.Required['1'].label, -- Notification
            ['nobeef2'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Beef.Required['2'].label, -- Notification
            ['enoughbeef1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Beef.Required['1'].label, -- Notification
            ['enoughbeef2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Beef.Required['2'].label, -- Notification
            ['novenison1'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Venison.Required['1'].label, -- Notification
            ['novenison2'] = 'You dont have any '..Config.Food.Cuttingboard.Sashimi.Venison.Required['2'].label, -- Notification
            ['enoughvenison1'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Venison.Required['1'].label, -- Notification
            ['enoughvenison2'] = 'You dont have enough '..Config.Food.Cuttingboard.Sashimi.Venison.Required['2'].label, -- Notification
            ['madesashimi'] = 'You successfully prepared some sashimi!', -- Notification
            ['makesashimi'] = 'Preparing Sashimi..', -- Progressbar
        },
    },
    Mixer = {
        ['mixerheader'] = 'Mixing Station', -- Menu header
        ['mixerheadertext'] = 'Mix ingredients for baking or drinks.', -- Menu header text
        ['mixerheadericon'] = 'fa-solid fa-briefcase', -- Menu header icon
        ['drinksheader'] = 'Mix Drinks', -- Menu header
        ['drinksheadertext'] = 'Prepare drinks for your customers!', -- Menu header text
        ['drinksheadericon'] = 'fa-solid fa-bottle-droplet', -- Menu header icon
        ['bakeheader'] = 'Mix Ingredients', -- Menu header
        ['bakeheadertext'] = 'Prepare baking ingredients!', -- Menu header text
	    ['bakeheadericon'] = 'fa-solid fa-bread-slice', -- Menu header text
        Ramune = {
            ['ramuneheader'] = 'Ramune', -- Menu header
            ['ramuneheadertext'] = 'Prepare ramune for your customers!', -- Menu header text
            ['ramuneheadericon'] = 'fa-solid fa-wine-glass-empty', -- Menu header icon
            ['ramuneicon'] = 'fa-solid fa-bottle-droplet', -- Menu header icon
            ['ramuneheader1'] = 'Ramune Cherry', -- Menu header
            ['ramuneheadertext1'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Ramune.Cherry.Required.amount..'x '..Config.Drinks.Mixer.Ramune.Cherry.Required.label, -- Menu header text
            ['ramuneheader2'] = 'Ramune Lemon', -- Menu header
            ['ramuneheadertext2'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Ramune.Lemon.Required.amount..'x '..Config.Drinks.Mixer.Ramune.Lemon.Required.label, -- Menu header text
            ['ramuneheader3'] = 'Ramune Pineapple', -- Menu header
            ['ramuneheadertext3'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Ramune.Pineapple.Required.amount..'x '..Config.Drinks.Mixer.Ramune.Pineapple.Required.label, -- Menu header text
            ['ramuneheader4'] = 'Ramune Coconut', -- Menu header
            ['ramuneheadertext4'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Ramune.Coconut.Required.amount..'x '..Config.Drinks.Mixer.Ramune.Coconut.Required.label, -- Menu header text
            ['ramuneheader5'] = 'Ramune Orange', -- Menu header
            ['ramuneheadertext5'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Ramune.Orange.Required.amount..'x '..Config.Drinks.Mixer.Ramune.Orange.Required.label, -- Menu header text
            ['ramuneheader6'] = 'Ramune Apple', -- Menu header
            ['ramuneheadertext6'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Ramune.Apple.Required.amount..'x '..Config.Drinks.Mixer.Ramune.Apple.Required.label, -- Menu header text
            ['ramuneheader7'] = 'Ramune Strawberry', -- Menu header
            ['ramuneheadertext7'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Ramune.Strawberry.Required.amount..'x '..Config.Drinks.Mixer.Ramune.Strawberry.Required.label, -- Menu header text
            ['ramuneheader8'] = 'Ramune Blueberry', -- Menu header
            ['ramuneheadertext8'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Ramune.Blueberry.Required.amount..'x '..Config.Drinks.Mixer.Ramune.Blueberry.Required.label, -- Menu header text
            ['nobottle'] = 'You dont have a '..Config.Drinks.Mixer.Ramune.Required['1'].label, -- Notification
            ['nowater'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Required['2'].label, -- Notification
            ['enoughcherry'] = 'You dont have enough '..Config.Drinks.Mixer.Ramune.Cherry.Required.label, -- Notification
            ['nocherry'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Cherry.Required.label, -- Notification
            ['enoughlemon'] = 'You dont have enough '..Config.Drinks.Mixer.Ramune.Lemon.Required.label, -- Notification
            ['nolemon'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Lemon.Required.label, -- Notification
            ['enoughpineapple'] = 'You dont have enough '..Config.Drinks.Mixer.Ramune.Pineapple.Required.label, -- Notification
            ['nopineapple'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Pineapple.Required.label, -- Notification
            ['enoughcoconut'] = 'You dont have enough '..Config.Drinks.Mixer.Ramune.Coconut.Required.label, -- Notification
            ['nococonut'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Coconut.Required.label, -- Notification
            ['enoughorange'] = 'You dont have enough '..Config.Drinks.Mixer.Ramune.Orange.Required.label, -- Notification
            ['noorange'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Orange.Required.label, -- Notification
            ['enoughapple'] = 'You dont have enough '..Config.Drinks.Mixer.Ramune.Apple.Required.label, -- Notification
            ['noapple'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Apple.Required.label, -- Notification
            ['enoughstrawberry'] = 'You dont have enough '..Config.Drinks.Mixer.Ramune.Strawberry.Required.label, -- Notification
            ['nostrawberry'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Strawberry.Required.label, -- Notification
            ['enoughblueberry'] = 'You dont have enough '..Config.Drinks.Mixer.Ramune.Blueberry.Required.label, -- Notification
            ['noblueberry'] = 'You dont have any '..Config.Drinks.Mixer.Ramune.Blueberry.Required.label, -- Notification
            ['mixedramune'] = 'Your mixed a bottle of ramune!', -- Notification
            ['mixramune'] = 'Mixing Ramune..', -- Progress bar
        },
        Boba = {
            ['bobaheader'] = 'Boba Tea', -- Menu header
            ['bobaheadertext'] = 'Prepare boba tea for your customers!', -- Menu header text
            ['bobaheadericon'] = 'fa-solid fa-mug-saucer', -- Menu header text
            ['bobaheader1'] = 'Boba Tea', -- Menu header
            ['bobaheadertext1'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Boba.Required['4'].amount..'x '..Config.Drinks.Mixer.Boba.Required['4'].label..'</p>'..Config.Drinks.Mixer.Boba.Boba.Required.amount..'x '..Config.Drinks.Mixer.Boba.Boba.Required.label, -- Menu header text
            ['bobaheader2'] = 'Matcha Boba Tea', -- Menu header
            ['bobaheadertext2'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Boba.Required['4'].amount..'x '..Config.Drinks.Mixer.Boba.Required['4'].label..'</p>'..Config.Drinks.Mixer.Boba.Matcha.Required.amount..'x '..Config.Drinks.Mixer.Boba.Matcha.Required.label, -- Menu header text
            ['bobaheader3'] = 'Ichigo Boba Tea', -- Menu header
            ['bobaheadertext3'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Boba.Required['4'].amount..'x '..Config.Drinks.Mixer.Boba.Required['4'].label..'</p>'..Config.Drinks.Mixer.Boba.Ichigo.Required['1'].amount..'x '..Config.Drinks.Mixer.Boba.Ichigo.Required['1'].label..'</p>'..Config.Drinks.Mixer.Boba.Ichigo.Required['2'].amount..'x '..Config.Drinks.Mixer.Boba.Ichigo.Required['2'].label, -- Menu header text
            ['bobaheader4'] = 'Lemon Boba Tea', -- Menu header
            ['bobaheadertext4'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Boba.Required['4'].amount..'x '..Config.Drinks.Mixer.Boba.Required['4'].label..'</p>'..Config.Drinks.Mixer.Boba.Lemon.Required['1'].amount..'x '..Config.Drinks.Mixer.Boba.Lemon.Required['1'].label..'</p>'..Config.Drinks.Mixer.Boba.Lemon.Required['2'].amount..'x '..Config.Drinks.Mixer.Boba.Lemon.Required['2'].label, -- Menu header text
            ['bobaheader5'] = 'Blueberry Boba Tea', -- Menu header
            ['bobaheadertext5'] = 'Ingredients:</p>'..Config.Drinks.Mixer.Boba.Required['4'].amount..'x '..Config.Drinks.Mixer.Boba.Required['4'].label..'</p>'..Config.Drinks.Mixer.Boba.Blueberry.Required['1'].amount..'x '..Config.Drinks.Mixer.Boba.Blueberry.Required['1'].label..'</p>'..Config.Drinks.Mixer.Boba.Blueberry.Required['2'].amount..'x '..Config.Drinks.Mixer.Boba.Blueberry.Required['2'].label, -- Menu header text
            ['nocup'] = 'You dont have a '..Config.Drinks.Mixer.Boba.Required['1'].label, -- Notification
            ['nosyrup'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Required['2'].label, -- Notification
            ['nomilk'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Required['3'].label, -- Notification
            ['nopearls'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Required['4'].label, -- Notification
            ['enoughpearls'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Required['4'].label, -- Notification
            ['enoughboba'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Boba.Required.label, -- Notification
            ['noboba'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Boba.Required.label, -- Notification
            ['enoughmatcha'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Matcha.Required.label, -- Notification
            ['nomatcha'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Matcha.Required.label, -- Notification
            ['enoughichigo1'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Ichigo.Required['1'].label, -- Notification
            ['noichigo1'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Ichigo.Required['1'].label, -- Notification
            ['enoughichigo2'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Ichigo.Required['2'].label, -- Notification
            ['noichigo2'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Ichigo.Required['2'].label, -- Notification
            ['enoughlemon'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Lemon.Required['1'].label, -- Notification
            ['nolemon'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Lemon.Required['1'].label, -- Notification
            ['enoughlemon2'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Lemon.Required['2'].label, -- Notification
            ['nolemon2'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Lemon.Required['2'].label, -- Notification
            ['enoughblueberry'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Blueberry.Required['1'].label, -- Notification
            ['noblueberry'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Blueberry.Required['1'].label, -- Notification
            ['enoughblueberry2'] = 'You dont have enough '..Config.Drinks.Mixer.Boba.Blueberry.Required['2'].label, -- Notification
            ['noblueberry2'] = 'You dont have any '..Config.Drinks.Mixer.Boba.Blueberry.Required['2'].label, -- Notification
            ['mixedboba'] = 'You prepared some Boba Tea!', -- Notification
            ['mixboba'] = 'Mixing Boba Tea..', -- Progressbar
        },
        Unbaked = {
            ['unbakedheader'] = 'Unbaked Confectionary', -- Menu header
            ['unbakedheadertext'] = 'View unbaked confectionary recipes!', -- Menu header text
            ['unbakedheadericon'] = 'fa-solid fa-cookie-bite', -- Menu header text
            ['unbakedheader1'] = 'Nishigashi Daifuku', -- Menu header
            ['unbakedheadertext1'] = 'Ingredients:</p>'..Config.Food.Mixer.Unbaked.Nishigashi.Required['1'].amount..'x '..Config.Food.Mixer.Unbaked.Nishigashi.Required['1'].label..'</p>'..Config.Food.Mixer.Unbaked.Nishigashi.Required['2'].amount..'x '..Config.Food.Mixer.Unbaked.Nishigashi.Required['2'].label..'</p>'..Config.Food.Mixer.Unbaked.Nishigashi.Required['3'].amount..'x '..Config.Food.Mixer.Unbaked.Nishigashi.Required['3'].label..'</p>'..Config.Food.Mixer.Unbaked.Nishigashi.Required['4'].amount..'x '..Config.Food.Mixer.Unbaked.Nishigashi.Required['4'].label, -- Menu header text
            ['unbakedheader2'] = 'Kuromame Daifuki', -- Menu header
            ['unbakedheadertext2'] = 'Ingredients:</p>'..Config.Food.Mixer.Unbaked.Kuromame.Required['1'].amount..'x '..Config.Food.Mixer.Unbaked.Kuromame.Required['1'].label..'</p>'..Config.Food.Mixer.Unbaked.Kuromame.Required['2'].amount..'x '..Config.Food.Mixer.Unbaked.Kuromame.Required['2'].label..'</p>'..Config.Food.Mixer.Unbaked.Kuromame.Required['3'].amount..'x '..Config.Food.Mixer.Unbaked.Kuromame.Required['3'].label..'</p>'..Config.Food.Mixer.Unbaked.Kuromame.Required['4'].amount..'x '..Config.Food.Mixer.Unbaked.Kuromame.Required['4'].label..'</p>'..Config.Food.Mixer.Unbaked.Kuromame.Required['5'].amount..'x '..Config.Food.Mixer.Unbaked.Kuromame.Required['5'].label, -- Menu header text
            ['unbakedheader3'] = 'Mitarashi Dango', -- Menu header
            ['unbakedheadertext3'] = 'Ingredients:</p>'..Config.Food.Mixer.Unbaked.Mitarashi.Required['1'].amount..'x '..Config.Food.Mixer.Unbaked.Mitarashi.Required['1'].label..'</p>'..Config.Food.Mixer.Unbaked.Mitarashi.Required['2'].amount..'x '..Config.Food.Mixer.Unbaked.Mitarashi.Required['2'].label..'</p>'..Config.Food.Mixer.Unbaked.Mitarashi.Required['3'].amount..'x '..Config.Food.Mixer.Unbaked.Mitarashi.Required['3'].label..'</p>'..Config.Food.Mixer.Unbaked.Mitarashi.Required['4'].amount..'x '..Config.Food.Mixer.Unbaked.Mitarashi.Required['4'].label..'</p>'..Config.Food.Mixer.Unbaked.Mitarashi.Required['5'].amount..'x '..Config.Food.Mixer.Unbaked.Mitarashi.Required['5'].label, -- Menu header text
            ['unbakedheader4'] = 'Matche Mille', -- Menu header
            ['unbakedheadertext4'] = 'Ingredients:</p>'..Config.Food.Mixer.Unbaked.Matche.Required['1'].amount..'x '..Config.Food.Mixer.Unbaked.Matche.Required['1'].label..'</p>'..Config.Food.Mixer.Unbaked.Matche.Required['2'].amount..'x '..Config.Food.Mixer.Unbaked.Matche.Required['2'].label..'</p>'..Config.Food.Mixer.Unbaked.Matche.Required['3'].amount..'x '..Config.Food.Mixer.Unbaked.Matche.Required['3'].label..'</p>'..Config.Food.Mixer.Unbaked.Matche.Required['4'].amount..'x '..Config.Food.Mixer.Unbaked.Matche.Required['4'].label..'</p>'..Config.Food.Mixer.Unbaked.Matche.Required['5'].amount..'x '..Config.Food.Mixer.Unbaked.Matche.Required['5'].label, -- Menu header text
            ['unbakedheader5'] = 'Mizu Yokan', -- Menu header
            ['unbakedheadertext5'] = 'Ingredients:</p>'..Config.Food.Mixer.Unbaked.Mizu.Required['1'].amount..'x '..Config.Food.Mixer.Unbaked.Mizu.Required['1'].label..'</p>'..Config.Food.Mixer.Unbaked.Mizu.Required['2'].amount..'x '..Config.Food.Mixer.Unbaked.Mizu.Required['2'].label..'</p>'..Config.Food.Mixer.Unbaked.Mizu.Required['3'].amount..'x '..Config.Food.Mixer.Unbaked.Mizu.Required['3'].label..'</p>'..Config.Food.Mixer.Unbaked.Mizu.Required['4'].amount..'x '..Config.Food.Mixer.Unbaked.Mizu.Required['4'].label..'</p>'..Config.Food.Mixer.Unbaked.Mizu.Required['5'].amount..'x '..Config.Food.Mixer.Unbaked.Mizu.Required['5'].label, -- Menu header text
            ['noplate'] = 'You need a '..Config.Food.Mixer.Unbaked.Required.label, -- Notification
            ['enoughnish1'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Nishigashi.Required['1'].label, -- Notification
            ['enoughnish2'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Nishigashi.Required['2'].label, -- Notification
            ['enoughnish3'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Nishigashi.Required['3'].label, -- Notification
            ['enoughnish4'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Nishigashi.Required['4'].label, -- Notification
            ['nonish1'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Nishigashi.Required['1'].label, -- Notification
            ['nonish2'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Nishigashi.Required['2'].label, -- Notification
            ['nonish3'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Nishigashi.Required['3'].label, -- Notification
            ['nonish4'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Nishigashi.Required['4'].label, -- Notification
            ['enoughkuro1'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Kuromame.Required['1'].label, -- Notification
            ['enoughkuro2'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Kuromame.Required['2'].label, -- Notification
            ['enoughkuro3'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Kuromame.Required['3'].label, -- Notification
            ['enoughkuro4'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Kuromame.Required['4'].label, -- Notification
            ['enoughkuro5'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Kuromame.Required['5'].label, -- Notification
            ['nokuro1'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Kuromame.Required['1'].label, -- Notification
            ['nokuro2'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Kuromame.Required['2'].label, -- Notification
            ['nokuro3'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Kuromame.Required['3'].label, -- Notification
            ['nokuro4'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Kuromame.Required['4'].label, -- Notification
            ['nokuro5'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Kuromame.Required['5'].label, -- Notification
            ['enoughmita1'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mitarashi.Required['1'].label, -- Notification
            ['enoughmita2'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mitarashi.Required['2'].label, -- Notification
            ['enoughmita3'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mitarashi.Required['3'].label, -- Notification
            ['enoughmita4'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mitarashi.Required['4'].label, -- Notification
            ['enoughmita5'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mitarashi.Required['5'].label, -- Notification
            ['nomita1'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mitarashi.Required['1'].label, -- Notification
            ['nomita2'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mitarashi.Required['2'].label, -- Notification
            ['nomita3'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mitarashi.Required['3'].label, -- Notification
            ['nomita4'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mitarashi.Required['4'].label, -- Notification
            ['nomita5'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mitarashi.Required['5'].label, -- Notification
            ['enoughmatche1'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Matche.Required['1'].label, -- Notification
            ['enoughmatche2'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Matche.Required['2'].label, -- Notification
            ['enoughmatche3'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Matche.Required['3'].label, -- Notification
            ['enoughmatche4'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Matche.Required['4'].label, -- Notification
            ['enoughmatche5'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Matche.Required['5'].label, -- Notification
            ['nomatche1'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Matche.Required['1'].label, -- Notification
            ['nomatche2'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Matche.Required['2'].label, -- Notification
            ['nomatche3'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Matche.Required['3'].label, -- Notification
            ['nomatche4'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Matche.Required['4'].label, -- Notification
            ['nomatche5'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Matche.Required['5'].label, -- Notification
            ['enoughmizu1'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mizu.Required['1'].label, -- Notification
            ['enoughmizu2'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mizu.Required['2'].label, -- Notification
            ['enoughmizu3'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mizu.Required['3'].label, -- Notification
            ['enoughmizu4'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mizu.Required['4'].label, -- Notification
            ['enoughmizu5'] = 'You dont have enough '..Config.Food.Mixer.Unbaked.Mizu.Required['5'].label, -- Notification
            ['nomizu1'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mizu.Required['1'].label, -- Notification
            ['nomizu2'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mizu.Required['2'].label, -- Notification
            ['nomizu3'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mizu.Required['3'].label, -- Notification
            ['nomizu4'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mizu.Required['4'].label, -- Notification
            ['nomizu5'] = 'You dont have any '..Config.Food.Mixer.Unbaked.Mizu.Required['5'].label, -- Notification
            ['mixedesert'] = 'You prepared a desert!', -- Notification
            ['mixdesert'] = 'Mixing Desert..', -- Progressbar
        }
    },
    Wash = {
        ['washedhands'] = 'You washed your hands!', -- Notification
        ['washedface'] = 'You washed your face!', -- Notification
        ['washedplate'] = 'You washed a Plate!', -- Notification
        ['washedbowl'] = 'You washed a Bowl!', -- Notification
        ['washedcup'] = 'You washed a Cup!', -- Notification
        ['washedglass'] = 'You washed a Glass!', -- Notification
        ['washedbento'] = 'You washed a Bento Box!', -- Notification
        ['takeplate'] = 'You took a '..Config.Wash.Dishes.Plate.Return.label..'!', -- Notification
        ['storeplate'] = 'You stored a '..Config.Wash.Dishes.Plate.Return.label..'!', -- Notification
        ['takecup'] = 'You took a '..Config.Wash.Dishes.Cup.Return.label..'!', -- Notification
        ['storecup'] = 'You stored a '..Config.Wash.Dishes.Cup.Return.label..'!', -- Notification
        ['takeglass'] = 'You took a '..Config.Wash.Dishes.Glass.Return.label..'!', -- Notification
        ['storeglass'] = 'You stored a '..Config.Wash.Dishes.Glass.Return.label..'!', -- Notification
        ['takebento'] = 'You took a '..Config.Wash.Dishes.Glass.Return.label..'!', -- Notification
        ['storebento'] = 'You stored a '..Config.Wash.Dishes.Glass.Return.label..'!', -- Notification
        ['nodirtyplate'] = 'You dont have any '..Config.Wash.Dishes.Plate.Required.label, -- Notification
        ['nodirtybowl'] = 'You dont have any '..Config.Wash.Dishes.Bowl.Required.label, -- Notification
        ['nodirtycup'] = 'You dont have any '..Config.Wash.Dishes.Cup.Required.label, -- Notification
        ['nodirtyglass'] = 'You dont have any '..Config.Wash.Dishes.Glass.Required.label, -- Notification
        ['nodirtybento'] = 'You dont have any '..Config.Wash.Dishes.Bento.Required.label, -- Notification
        ['noplate'] = 'You dont have a '..Config.Wash.Dishes.Plate.Return.label, -- Notification
        ['nobowl'] = 'You dont have a '..Config.Wash.Dishes.Bowl.Return.label, -- Notification
        ['nocup'] = 'You dont have a '..Config.Wash.Dishes.Cup.Return.label, -- Notification
        ['noglass'] = 'You dont have a '..Config.Wash.Dishes.Glass.Return.label, -- Notification
        ['nobento'] = 'You dont have a '..Config.Wash.Dishes.Bento.Return.label, -- Notification
        ['washhands'] = 'Washing Hands..', -- Progressbar
        ['washface'] = 'Washing Face..', -- Progressbar
        ['washdishes'] = 'Washing Dishes..', -- Progressbar
        ['takingplate'] = 'Taking A Plate..', -- Progressbar
        ['storingplate'] = 'Storing A Plate..', -- Progressbar
        ['takingcup'] = 'Taking A Cup..', -- Progressbar
        ['storingcup'] = 'Storing A Cup..', -- Progressbar 
        ['takingglass'] = 'Taking A Glass..', -- Progressbar
        ['storingglass'] = 'Storing A Glass..', -- Progressbar
    },
    HotDrinks = {
        ['hotdrinksmenuheader'] = 'Coffee Machine', -- Menu header
        ['hotdrinksmenuheadertext'] = 'Prepare hot drinks for your customers!', -- Menu header text
        ['hotdrinksmenuheadericon'] = 'fa-solid fa-briefcase', -- Menu header icon
        ['coffeeheader'] = 'Coffee', -- Menu header
        ['coffeeheadertext'] = 'Ingredients:</p>'..Config.Drinks.Hot.Coffee.Required.amount..'x '..Config.Drinks.Hot.Coffee.Required.label, -- Menu header text
        ['coffeeheadericon'] = 'fa-solid fa-mug-hot', -- Menu header icon
        ['teaheader'] = 'Tea', -- Menu header
        ['teaheadertext'] = 'Ingredients:</p>'..Config.Drinks.Hot.Tea.Required.amount..'x '..Config.Drinks.Hot.Tea.Required.label, -- Menu header text
        ['teaheadericon'] = 'fa-solid fa-mug-hot', -- Menu header icon
        ['greenteaheader'] = 'Green Tea', -- Menu header
        ['greenteaheadertext'] = 'Ingredients:</p>'..Config.Drinks.Hot.GreenTea.Required.amount..'x '..Config.Drinks.Hot.GreenTea.Required.label, -- Menu header text
        ['greenteaheadericon'] = 'fa-solid fa-mug-hot', -- Menu header icon
        ['enoughcoffee'] = 'You dont have enough '..Config.Drinks.Hot.Coffee.Required.label, -- Notification
        ['enoughtea'] = 'You dont have enough '..Config.Drinks.Hot.Tea.Required.label, -- Notification
        ['enoughgreentea'] = 'You dont have enough '..Config.Drinks.Hot.GreenTea.Required.label, -- Notification
        ['nocoffee'] = 'You dont have any '..Config.Drinks.Hot.Coffee.Required.label, -- Notification
        ['notea'] = 'You dont have any '..Config.Drinks.Hot.Tea.Required.label, -- Notification
        ['nogreentea'] = 'You dont have any '..Config.Drinks.Hot.GreenTea.Required.label, -- Notification
        ['nocup'] = 'Looks like your missing a '..Config.Drinks.Hot.Required.label, -- Notification
        ['madecoffee'] = 'You successfully made a '..Config.Drinks.Hot.Coffee.Return.label, -- Notification
        ['madetea'] = 'You successfully made a '..Config.Drinks.Hot.Tea.Return.label, -- Notification
        ['madegreentea'] = 'You successfully made a '..Config.Drinks.Hot.GreenTea.Return.label, -- Notification
        ['makehot'] = 'Making a Hot Drink..', -- Progressbar
    },
    Billing = {
        ['paymenuheader'] = 'UwU Cafe', -- Menu header
        ['paymenuheadertext'] = 'Charge Customer', -- Menu header text
        ['invoicesent'] = 'Invoice sent successfully!', -- Notification
        ['invoicereceived'] = 'Invoice received from UwU Cafe!', -- Notification
        ['minamount'] = 'You cant charge someone nothing idiot..', -- Notification
        ['billself'] = 'You cant bill yourself idiot..', -- Notification
        ['billoffline'] = 'You cant bill someone whos not in city idiot..', -- Notification
        ['noaccess'] = 'You are not authorised to make sales..', -- Notification
        ['paytext'] = 'paypal id', -- Input text when charging customers
        ['payamount'] = '$ amount', -- Input text when charging customers
    },
    Plushies = {
        ['shownplushie'] = 'You showed everyone your favorite plushie!', -- Notification
        ['showplushie'] = 'Showing Off Plushie..', -- Progressbar
    },
    Cats = {
        ['petcat'] = 'You pet the cat!', -- Notification
    },
    Garage = {
        ['returnedvan'] = 'Thank you for returning the van!', -- Notification
        ['rentedvan'] = 'You took out a van! Return it when your done!', -- Notification
        ['nomoney'] = 'You cant afford the deposit dumbass..', -- Notification
        ['rentheader'] = 'UwU Garage', -- Menu header
        ['rentheadericon'] = 'fa-solid fa-warehouse', -- Menu header
        ['rentmenuheader'] = 'Company Van', -- Menu header
        ['rentmenutext'] = 'A deposit of $'..Config.Garage.Deposit..' is required.', -- Menu text
        ['rentmenuicon'] = 'fa-solid fa-car', -- Menu icon
        ['returnmenuheader'] = 'Return Van', -- Menu header
        ['returnmenutext'] = 'Return Vehicle to receive $'..math.floor(Config.Garage.Deposit/2), -- Menu text
        ['returnmenuicon'] = 'fa-solid fa-car', -- Menu icon
    },
    Shared = {
        ['returnmenu'] = 'Return', -- Menu header
        ['returnmenuicon'] = 'fa-solid fa-backward', -- Menu header icon
        ['exitmenu'] = 'Exit', -- Menu header
        ['exitmenuicon'] = 'fa-solid fa-circle-xmark', -- Menu header icon
        ['cancelled'] = 'Action cancelled..', -- Notification
        ['noinvent'] = 'Looks like your pockets are full..', -- Notification
        ['outrange'] = 'Looks like you are too far away..', -- Notification
        ['forceentry'] = 'Forcing Entry..' -- Progressbar
    } 
}